#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "findyml"

dir, query = case ARGV.size
when 1
  [Dir.pwd, ARGV.last]
when 2
  ARGV
else
  puts "Usage: #{$0} [path] query"
  exit(1)
end

Findyml.find_and_print(query, dir)
